export const CAMERA_DATA = [

  {
    id: 'alexa65',
    name: 'ARRI Alexa 65',
    tier: 'Tier A',
    sub: '6.5K Large Format',
    tag: 'shot on ARRI Alexa 65, 6.5K large format digital cinema, ARRI color science, ultra-cinematic',
    image: '/media/cameras/alexa65.png',
    imageFallback: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?w=400&q=80',
    lenses: [
      { name: 'ARRI Signature Prime',   type: 'spherical',  note: 'T1.8 · sharpest LF prime · zero breathing' },
      { name: 'ARRI Prime 65',          type: 'spherical',  note: 'T1.9 · original LF prime · classic ARRI rendering' },
      { name: 'Hasselblad HK Prime',    type: 'spherical',  note: 'T2.2 · medium format character · creamy micro-contrast' },
      { name: 'Hawk65 Anamorphic',      type: 'anamorphic', note: 'T2.2 · 2x anamorphic · oval bokeh · horizontal flares' },
    ],
    focals: ['14mm','18mm','21mm','25mm','35mm','47mm','50mm','75mm','100mm','125mm','150mm','185mm'],
    fstops: ['T1.8','T2','T2.8','T4','T5.6','T8','T11'],
  },

  {
    id: 'alexalf',
    name: 'ARRI Alexa LF',
    tier: 'Tier A',
    sub: '4.5K Large Format',
    tag: 'shot on ARRI Alexa LF, large format cinema, ARRI color science, filmic shallow depth of field',
    image: '/media/cameras/alexalf.png',
    imageFallback: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80',
    lenses: [
      { name: 'ARRI Signature Prime',    type: 'spherical',  note: 'T1.8 · definitive LF prime · used on Euphoria, 1917' },
      { name: 'Leica Summilux-C',        type: 'spherical',  note: 'T1.4 · warm organic rendering · gorgeous flare character' },
      { name: 'ARRI Master Anamorphic',  type: 'anamorphic', note: 'T1.9 · LF anamorphic · oval bokeh · subtle blue streak flares' },
      { name: 'Cooke S7/i Full Frame+',  type: 'spherical',  note: 'T2 · Cooke Look · organic warmth · trusted by Netflix' },
    ],
    focals: ['14mm','18mm','21mm','25mm','35mm','47mm','50mm','75mm','100mm','125mm','150mm','185mm'],
    fstops: ['T1.8','T2','T2.8','T4','T5.6','T8','T11'],
  },

  {
    id: 'alexa35',
    name: 'ARRI Alexa 35',
    tier: 'Tier A',
    sub: 'Super 35 · 17 Stops DR',
    tag: 'shot on ARRI Alexa 35, Super 35 cinema, ARRI color science v4, 17 stops dynamic range',
    image: '/media/cameras/alexa35.png',
    imageFallback: 'https://images.unsplash.com/photo-1598387993441-a364f854cfbd?w=400&q=80',
    lenses: [
      { name: 'ARRI Master Prime',             type: 'spherical',  note: 'T1.3 · fastest ARRI prime · ultra-resolving · zero distortion' },
      { name: 'ARRI Signature Prime',          type: 'spherical',  note: 'T1.8 · modern character · smooth rendering' },
      { name: 'Zeiss Supreme Prime Radiance',  type: 'spherical',  note: 'T1.5 · engineered flares · expressionist look' },
      { name: 'Cooke Anamorphic/i SF',         type: 'anamorphic', note: 'T2.3 · Full Frame anamorphic · oval bokeh · warm blue flares' },
    ],
    focals: ['14mm','18mm','21mm','25mm','32mm','35mm','40mm','50mm','65mm','75mm','100mm','135mm','150mm','185mm'],
    fstops: ['T1.3','T1.8','T2','T2.8','T4','T5.6','T8','T11'],
  },

  {
    id: 'venice2',
    name: 'Sony VENICE 2',
    tier: 'Tier A',
    sub: 'Full Frame 8.6K',
    tag: 'shot on Sony Venice 2, full frame 8.6K cinema, natural skin tone rendering, organic filmic look',
    image: '/media/cameras/venice2.png',
    imageFallback: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&q=80',
    lenses: [
      { name: 'Zeiss Supreme Prime',     type: 'spherical',  note: 'T1.5 · clinically sharp · natural modern rendering' },
      { name: 'Canon Sumire Prime',      type: 'spherical',  note: 'T1.3 · vintage warmth · painterly bokeh · cream rendering' },
      { name: 'Cooke S7/i Full Frame+',  type: 'spherical',  note: 'T2 · Cooke Look · organic skin tones' },
      { name: 'Atlas Orion Anamorphic',  type: 'anamorphic', note: 'T2 · 2x anamorphic · warm amber flares · smooth oval bokeh' },
    ],
    focals: ['14mm','17mm','21mm','25mm','35mm','40mm','50mm','65mm','85mm','100mm','135mm','150mm','185mm'],
    fstops: ['T1.3','T1.5','T2','T2.8','T4','T5.6','T8','T11'],
  },

  {
    id: 'raptor',
    name: 'RED V-RAPTOR 8K VV',
    tier: 'Tier A',
    sub: 'Vista Vision 8K',
    tag: 'shot on RED V-Raptor VV, 8K Vista Vision, hyper-detailed digital cinema, VFX-ready',
    image: '/media/cameras/raptor.png',
    imageFallback: 'https://images.unsplash.com/photo-1524656855800-59465ebcec69?w=400&q=80',
    lenses: [
      { name: 'Canon Sumire Prime',                type: 'spherical',  note: 'T1.3 · vintage warmth on VV sensor · stunning separation' },
      { name: 'Leica Thalia',                      type: 'spherical',  note: 'T2.6 · built for large format · soft micro-contrast · German character' },
      { name: 'Zeiss Supreme Prime',               type: 'spherical',  note: 'T1.5 · pin-sharp for VFX · covers VV edge to edge' },
      { name: 'Panavision Ultra Vista Anamorphic', type: 'anamorphic', note: 'T2 · 1.65x squeeze · VV anamorphic · ultra-wide scope look' },
    ],
    focals: ['14mm','18mm','21mm','25mm','35mm','40mm','50mm','65mm','80mm','100mm','125mm','150mm','185mm'],
    fstops: ['T1.3','T1.5','T2','T2.8','T4','T5.6','T8','T11','T16'],
  },

  {
    id: 'dxl2',
    name: 'Panavision DXL2',
    tier: 'Tier A',
    sub: 'Large Format 8K',
    tag: 'shot on Panavision DXL2, large format 8K, classic Panavision aesthetic, Hollywood character',
    image: '/media/cameras/dxl2.png',
    imageFallback: 'https://images.unsplash.com/photo-1603190287605-e6ade32fa852?w=400&q=80',
    lenses: [
      { name: 'Panavision Primo Artiste',        type: 'spherical',  note: 'T1.4 · fastest Panavision prime · iconic Hollywood look' },
      { name: 'Leica Thalia',                    type: 'spherical',  note: 'T2.6 · organic German glass · creamy falloff' },
      { name: 'Panavision Anamorphic C-Series',  type: 'anamorphic', note: 'T2 · classic 2x anamorphic · horizontal flares · oval bokeh' },
      { name: 'Panavision Primo 70 Anamorphic',  type: 'anamorphic', note: 'T2 · modern anamorphic · sharp center · expressive flares' },
    ],
    focals: ['17.5mm','21mm','25mm','35mm','40mm','50mm','65mm','75mm','100mm','125mm','150mm','185mm'],
    fstops: ['T1.4','T2','T2.8','T4','T5.6','T8','T11','T16'],
  },

  {
    id: 'arriflex',
    name: 'ARRIFLEX 35 BL',
    tier: 'Classic Film',
    sub: '35mm Kodak Vision3',
    tag: 'shot on ARRIFLEX 35 BL, 35mm Kodak Vision3 film, classic Hollywood grain, natural halation, warm filmic',
    image: '/media/cameras/arriflex.png',
    imageFallback: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=400&q=80',
    lenses: [
      { name: 'Zeiss Super Speed',              type: 'spherical',  note: 'T1.3 · legendary Super Speed primes · warm halation · classic Hollywood' },
      { name: 'Cooke Speed Panchro S2/S3',      type: 'spherical',  note: 'T2 · THE classic film lens · warm Cooke Look · used on Kubrick films' },
      { name: 'Panavision C-Series Anamorphic', type: 'anamorphic', note: 'T2 · 2x anamorphic on 35mm · oval bokeh · horizontal cyan/blue flares' },
      { name: 'Canon K-35 Prime',               type: 'spherical',  note: 'T1.3 · rare · swirly soft bokeh · used on Star Wars: A New Hope' },
    ],
    focals: ['18mm','24mm','25mm','35mm','40mm','50mm','55mm','75mm','85mm','100mm'],
    fstops: ['T1.3','T2','T2.1','T2.8','T4','T5.6','T8','T11'],
  },

  {
    id: 'panaflex',
    name: 'Panavision Panaflex',
    tier: 'Classic Film',
    sub: '35mm Anamorphic',
    tag: 'shot on Panavision Panaflex, 35mm anamorphic film, oval bokeh, anamorphic streak flares, widescreen 2.39:1',
    image: '/media/cameras/panaflex.png',
    imageFallback: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&q=80',
    lenses: [
      { name: 'Panavision C-Series Anamorphic', type: 'anamorphic', note: 'T2 · used on Chinatown, Blade Runner, The Godfather' },
      { name: 'Panavision E-Series Anamorphic', type: 'anamorphic', note: 'T2 · expressive oval bokeh · strong blue horizontal flares' },
      { name: 'Panavision Primo Anamorphic',    type: 'anamorphic', note: 'T1.9 · modern sharp anamorphic · clean flares' },
      { name: 'Panavision Sphero 65',           type: 'spherical',  note: 'T2 · spherical option · sharp coverage · non-scope setups' },
    ],
    focals: ['24mm','28mm','35mm','40mm','50mm','60mm','75mm','100mm','125mm','150mm','185mm'],
    fstops: ['T1.9','T2','T2.8','T4','T5.6','T8','T11','T16'],
  },

];

export const FSTOP_DESCRIPTIONS = {
  'T1.3': 'Razor-thin DOF · extreme isolation · dreamlike',
  'T1.4': 'Ultra-shallow · beautiful separation',
  'T1.5': 'Very shallow · creamy bokeh · low light',
  'T1.8': 'Shallow · sharp subject · silky background',
  'T1.9': 'Anamorphic standard · oval bokeh',
  'T2':   'Sweet spot · perfect bokeh balance',
  'T2.1': 'Clean yet filmic · Zeiss classic stop',
  'T2.3': 'Balanced · anamorphic character stop',
  'T2.6': 'Leica character stop · warm organic',
  'T2.8': 'Standard cinematic · moderate depth of field',
  'T4':   'Deep focus · documentary realism',
  'T5.6': 'Landscape depth · front-to-back sharp',
  'T8':   'Maximum sharpness · daylight exterior',
  'T11':  'Ultra-deep DOF · specialty use',
  'T16':  'Extreme DOF · fully stopped down',
};
